# Generated by Django 6.1 on 2026-08-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('skills_score', models.FloatField(default=0)),
                ('keywords_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
            ],
        ),
    ]
