# Generated by Django 6.1 on 2026-08-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_alter_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='similarity_score',
            field=models.FloatField(default=0),
        ),
    ]
